CFLAGS = -fno-objc-arc

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ObjcIPCBackboarddHooks
ObjcIPCBackboarddHooks_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
